services:
  starbucks:
    build:
      context: ./Starbucks
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    ports:
      - '8080:80'
    networks:
      - test-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 3

networks:
  test-network:
    driver: bridge